In [8]:
import pandas as pd

class TimeParser:
    # Some shit to parse time

# Read in data
data_200_splits = pd.read_csv('data/db_800m_splits.csv')
data_400_splits = data_200_splits.copy()

# Split into two datasets: 4 splits and 2 splits
splits_200m = data_200_splits.dropna()
splits_200m

splits_400m = data_400_splits[data_400_splits.isna().any(axis=1)]
splits_400m

                athlete    lap_1    lap_2 lap_3 lap_4 total_time
0      shawn stephenson  1:00.20  1:03.71   NaN   NaN    2:03.91
1      shawn stephenson  1:02.19  1:05.90   NaN   NaN    2:08.09
2      shawn stephenson  1:00.81  1:03.79   NaN   NaN    2:04.60
5     margaret rockhold  1:25.34  1:34.28   NaN   NaN    2:59.62
6    kennedy richardson  1:23.60  1:33.13   NaN   NaN    2:56.73
..                  ...      ...      ...   ...   ...        ...
185        anglin young  0:59.47  1:08.13   NaN   NaN    2:07.60
186    shawn stephenson  0:58.71  1:10.47   NaN   NaN    2:09.18
187    mary mac collins  1:08.53  1:11.67   NaN   NaN    2:20.20
188        lillie gould  1:13.97  1:15.31   NaN   NaN    2:29.28
189    baden sanderford  0:59.50  1:04.46   NaN   NaN    2:03.96

[158 rows x 6 columns]